"""Audit script — lab_lite TOTAL_CANDLES window scope (Caveat #21 §13.2).

Compares preset pools generated under three modes for a sample of symbols:

  Mode A (CURRENT, baseline 2026-04-19):
    Recent ~5000 bars (TOTAL_CANDLES=5000 hardcoded), regime-aware (GMM
    applied to recent window → 3 clusters → per-cluster preset selection).

  Mode B1 (FULL-HISTORY regime-agnostic):
    Full parquet history (~50-76K bars per sym). USE_CLUSTERING=False
    → single pool of presets ranked by global PnL/EMA score.

  Mode B2 (FULL-HISTORY per-cluster):
    Full parquet history + GMM applied to full series (cluster labels per
    bar) → per-cluster preset selection over full history. The MAs are
    computed on the CONTINUOUS series and only the scoring is masked by
    cluster.

Output:
  - audit_lab_lite_results_<TS>/preset_pools_{SYM}_{mode}.json
  - audit_lab_lite_results_<TS>/overlap_report.json (Jaccard A vs B1, A vs B2, B1 vs B2)
  - stdout summary

Designed for read-only audit (no productive code modified; uses backed-up
GMM models from regime_models/). Does NOT touch live/* or productive
pipeline.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Set, Tuple

import numpy as np
import pandas as pd
import joblib

import lab_lite_zonas_v5e as ll


# ---------------------------------------------------------------------------
# Parquet loader (replaces fetch_all_candles for audit modes B1/B2)
# ---------------------------------------------------------------------------

def load_full_parquet(symbol: str, parquet_dir: str = "data_cache") -> pd.DataFrame:
    """Load full-history parquet for symbol. Returns df with [timestamp, OHLCV].

    Normalizes schema: data_cache parquet uses 'timestamp_ms' int64; lab_lite
    expects 'timestamp' as datetime64. Convert ms → datetime.
    """
    sym_clean = symbol.replace("/", "").replace("USDT", "")
    p = Path(parquet_dir) / f"{sym_clean}USDT_1h.parquet"
    if not p.exists():
        raise FileNotFoundError(f"parquet not found: {p}")
    df = pd.read_parquet(p)
    if "timestamp" not in df.columns and "timestamp_ms" in df.columns:
        df = df.rename(columns={"timestamp_ms": "timestamp"})
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
    elif "timestamp" in df.columns and not pd.api.types.is_datetime64_any_dtype(df["timestamp"]):
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
    cols = ["timestamp", "open", "high", "low", "close", "volume"]
    return df[cols].reset_index(drop=True)


# ---------------------------------------------------------------------------
# Signature extraction
# ---------------------------------------------------------------------------

def preset_signature(fast_entry, slow_entry) -> str:
    """Build canonical signature 'FAST(period)/SLOW(period)' for overlap comparison.

    Trend is excluded — derived post-hoc as slow×4 (see result_to_preset_tuple).
    p1/p2 ignored (cluster of similar variants under same family/period).
    """
    f_type, f_period, _, _ = fast_entry
    s_type, s_period, _, _ = slow_entry
    f_name = ll.MA_NAMES.get(f_type, f"T{f_type}")
    s_name = ll.MA_NAMES.get(s_type, f"T{s_type}")
    return f"{f_name}({f_period})/{s_name}({s_period})"


# ---------------------------------------------------------------------------
# Mode A — CURRENT (read backed-up presets from baseline preservation)
# ---------------------------------------------------------------------------

def extract_mode_a_signatures(symbol: str, baseline_dir: str = None) -> Set[str]:
    """Mode A: extract preset signatures from existing presets CSV
    (already generated by productive lab_lite with TOTAL_CANDLES=5000).

    Uses output/production/presets_<SYM>USDT.csv if available, else
    falls back to baseline_dir/presets_<SYM>USDT.csv.
    """
    sym_clean = symbol.replace("/", "").replace("USDT", "")
    candidate_paths = []
    if baseline_dir:
        candidate_paths.append(Path(baseline_dir) / f"presets_{sym_clean}USDT.csv")
    candidate_paths.append(Path("output/production") / f"presets_{sym_clean}USDT.csv")
    csv_path = None
    for cp in candidate_paths:
        if cp.exists():
            csv_path = cp
            break
    if csv_path is None:
        raise FileNotFoundError(
            f"presets_{sym_clean}USDT.csv not found in {candidate_paths}"
        )
    df = pd.read_csv(csv_path)
    sigs = set()
    for _, row in df.iterrows():
        sig = f"{row['fast_type']}({int(row['fast_period'])})/{row['slow_type']}({int(row['slow_period'])})"
        sigs.add(sig)
    return sigs


# ---------------------------------------------------------------------------
# Mode B1/B2 — FULL-HISTORY simulation
# ---------------------------------------------------------------------------

def run_simulation_full_history(
    symbol: str,
    use_clustering: bool,
    parquet_dir: str = "data_cache",
    model_dir: str = "regime_models",
    min_trades_cluster: int = 30,
    min_pf_cluster: float = 1.2,
    top_n_cluster: int = 6,
    min_trades_global: int = 10,
    top_n_global: int = 14,
    return_full_results: bool = False,
) -> Dict:
    """Run lab_lite v5e simulation over FULL parquet history.

    Args:
        use_clustering: True for Mode B2 (per-cluster), False for Mode B1 (agnostic).

    Returns dict with:
        signatures_global: Set[str] — global preset pool signatures
        signatures_per_cluster: Dict[int, Set[str]] — per-cluster pools (B2 only)
        signatures_union: Set[str] — union of global + per-cluster pools
        n_bars: int
        time_range: Tuple[str, str]
        elapsed_s: float
    """
    t0 = time.time()
    df = load_full_parquet(symbol, parquet_dir=parquet_dir)
    n_bars_total = len(df)
    ts_start = str(df["timestamp"].iloc[0])
    ts_end = str(df["timestamp"].iloc[-1])

    # Pre-calculate all MAs (continuous series)
    close, fast_arr, slow_arr, trend_arr, fast_cat, slow_cat, trend_cat = ll.precalculate_all_mas(df)
    n_fast, n_slow, n_trend = len(fast_cat), len(slow_cat), len(trend_cat)
    n_configs = n_fast * n_slow * n_trend

    # Warmup
    max_slow_period = max(p for _, p, _, _ in slow_cat)
    max_trend_period = max((p for _, p, _, _ in trend_cat if p > 0), default=0)
    warmup = max(max_slow_period, max_trend_period) * 3

    # Cluster labels
    if use_clustering:
        labels, cluster_info = ll.load_and_apply_regime_model(
            symbol, df, model_dir=model_dir
        )
        n_clusters = cluster_info["n_clusters"]
        cluster_labels_np = labels.astype(np.int64)
    else:
        n_clusters = 1
        cluster_labels_np = np.zeros(n_bars_total, dtype=np.int64)

    test_start = warmup

    # EMA reference
    ema_f = ll.calc_ema(close, ll.EMA_FAST)
    ema_s = ll.calc_ema(close, ll.EMA_SLOW)
    ema_t = ll.calc_ema(close, ll.EMA_TREND)
    ema_pnl, ema_trades, ema_raw_crosses, _, _ = ll.simulate_ema_pnl(
        close, ema_f, ema_s, ema_t, ll.COMMISSION_ROUND_TRIP,
        test_start, warmup, cluster_labels_np, n_clusters,
    )

    # Run candidates simulation
    cand_pnl, cand_trades, cand_raw_crosses, cl_pnl, cl_trades, cl_gp, cl_gl = \
        ll.run_simulation_v5e(
            close, fast_arr, slow_arr, trend_arr,
            n_fast, n_slow, n_trend,
            ll.COMMISSION_ROUND_TRIP, test_start, warmup,
            cluster_labels_np, n_clusters,
        )

    # Global scoring (analogous to process_symbol lines 771-792)
    valid = cand_trades >= min_trades_global
    excess_cross = np.where(
        ema_raw_crosses > 0,
        np.maximum(0.0, (cand_raw_crosses.astype(np.float64) - ema_raw_crosses) / ema_raw_crosses),
        0.0,
    )
    excess_cross = np.minimum(excess_cross, 1.0)
    cross_penalty = 1.0 - 0.3 * excess_cross
    if ema_pnl > 0:
        pnl_ratio = cand_pnl / ema_pnl
    else:
        pnl_ratio = cand_pnl / 10.0
    score = pnl_ratio * cross_penalty
    score_valid = np.where(valid, score, -999.0)
    sorted_idx = np.argsort(-score_valid)

    # Build global top-N: collect ranked candidate dicts for both signature
    # extraction AND CSV writing (productive-format compatible).
    global_signatures: Set[str] = set()
    global_results: List[Dict] = []  # res dicts compatible with productive CSV writer
    for idx in sorted_idx:
        if score_valid[idx] <= -999.0:
            break
        fi = idx // (n_slow * n_trend)
        remainder = idx % (n_slow * n_trend)
        si = remainder // n_trend
        ti = remainder % n_trend
        sig = preset_signature(fast_cat[fi], slow_cat[si])
        if sig in global_signatures:
            continue
        global_signatures.add(sig)
        global_results.append({
            "fast": fast_cat[fi], "slow": slow_cat[si], "trend": trend_cat[ti],
            "score": float(score[idx]),
            "pnl": float(cand_pnl[idx]),
            "trades": int(cand_trades[idx]),
            "raw_crosses": int(cand_raw_crosses[idx]),
            "excess_cross": float(excess_cross[idx]),
        })
        if len(global_results) >= top_n_global:
            break

    # Per-cluster selection (B2 only — B1 has n_clusters=1, just one cluster)
    signatures_per_cluster: Dict[int, Set[str]] = {}
    cluster_presets_dicts: Dict[int, List[Dict]] = {}
    if use_clustering:
        all_configs_arr = cand_pnl  # use cand_pnl as placeholder
        cluster_presets_dicts = ll.select_top_per_cluster(
            all_configs_arr, cl_pnl, cl_trades, cl_gp, cl_gl,
            n_clusters, fast_cat, slow_cat, trend_cat,
            n_slow, n_trend,
            min_trades=min_trades_cluster, min_pf=min_pf_cluster,
            top_n=top_n_cluster,
        )
        for k in range(n_clusters):
            sigs_k = set()
            for res in cluster_presets_dicts.get(k, []):
                sigs_k.add(preset_signature(res["fast"], res["slow"]))
            signatures_per_cluster[k] = sigs_k

    union = set(global_signatures)
    for s in signatures_per_cluster.values():
        union |= s

    elapsed = time.time() - t0
    result = {
        "signatures_global": global_signatures,
        "signatures_per_cluster": signatures_per_cluster,
        "signatures_union": union,
        "n_bars_total": n_bars_total,
        "time_range": (ts_start, ts_end),
        "n_clusters": n_clusters,
        "n_configs": n_configs,
        "warmup": warmup,
        "elapsed_s": elapsed,
        "use_clustering": use_clustering,
    }
    if return_full_results:
        result["global_results"] = global_results
        result["cluster_results"] = cluster_presets_dicts
    return result


# ---------------------------------------------------------------------------
# CSV writer (productive format compatible with regime_walk_forward load_presets)
# ---------------------------------------------------------------------------

def write_presets_csv(out_csv: Path, global_results: List[Dict],
                       cluster_results: Dict[int, List[Dict]] = None) -> None:
    """Write presets CSV in productive lab_lite v5e format.

    Columns:
        rank,fast_type,fast_period,fast_p1,fast_p2,
        slow_type,slow_period,slow_p1,slow_p2,
        trend_type,trend_period,trend_p1,trend_p2,
        score,pnl,trades,raw_crosses,excess_cross,family,
        cluster_id,cluster_pf,cluster_pnl,cluster_trades

    Trend derived as slow×4 same type (matches result_to_preset_tuple).
    Global rows have cluster_id=-1 and blank cluster_pf/pnl/trades.
    Per-cluster rows have rank='C{k}_{r}' and cluster_id=k.
    """
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with open(out_csv, "w", encoding="utf-8") as f:
        f.write(
            "rank,fast_type,fast_period,fast_p1,fast_p2,"
            "slow_type,slow_period,slow_p1,slow_p2,"
            "trend_type,trend_period,trend_p1,trend_p2,"
            "score,pnl,trades,raw_crosses,excess_cross,family,"
            "cluster_id,cluster_pf,cluster_pnl,cluster_trades\n"
        )
        for r, res in enumerate(global_results, 1):
            pt = ll.result_to_preset_tuple(res)
            fam = f"{ll.ma_family(res['fast'])}/{ll.ma_family(res['slow'])}"
            f.write(
                f"{r},{pt[0]},{pt[1]},{pt[2]},{pt[3]},"
                f"{pt[4]},{pt[5]},{pt[6]},{pt[7]},"
                f"{pt[8]},{pt[9]},{pt[10]},{pt[11]},"
                f"{res['score']:.6f},{res['pnl']:.4f},{res['trades']},"
                f"{res['raw_crosses']},{res['excess_cross']:.4f},{fam},"
                f"-1,,,\n"
            )
        if cluster_results:
            for k in sorted(cluster_results.keys()):
                for r, res in enumerate(cluster_results[k], 1):
                    pt = ll.result_to_preset_tuple(res)
                    fam = f"{ll.ma_family(res['fast'])}/{ll.ma_family(res['slow'])}"
                    f.write(
                        f"C{k}_{r},{pt[0]},{pt[1]},{pt[2]},{pt[3]},"
                        f"{pt[4]},{pt[5]},{pt[6]},{pt[7]},"
                        f"{pt[8]},{pt[9]},{pt[10]},{pt[11]},"
                        f"{res.get('score', 0):.6f},{res.get('global_pnl', 0):.4f},"
                        f"{res.get('cluster_trades', 0)},"
                        f"0,0.0000,{fam},"
                        f"{k},{res.get('cluster_pf', 0):.4f},"
                        f"{res.get('cluster_pnl', 0):.4f},"
                        f"{res.get('cluster_trades', 0)}\n"
                    )


# ---------------------------------------------------------------------------
# Overlap metrics
# ---------------------------------------------------------------------------

def jaccard(a: Set[str], b: Set[str]) -> float:
    if not a and not b:
        return 1.0
    inter = a & b
    union = a | b
    return len(inter) / len(union) if union else 0.0


def overlap_report(pools: Dict[str, Set[str]]) -> Dict:
    """Compute pairwise Jaccard + symmetric differences for the modes."""
    modes = list(pools.keys())
    rep = {"jaccard": {}, "only_in": {}, "intersection": {}, "sizes": {}}
    for m in modes:
        rep["sizes"][m] = len(pools[m])
    for i, m1 in enumerate(modes):
        for m2 in modes[i + 1:]:
            j = jaccard(pools[m1], pools[m2])
            inter = pools[m1] & pools[m2]
            only1 = pools[m1] - pools[m2]
            only2 = pools[m2] - pools[m1]
            key = f"{m1}_vs_{m2}"
            rep["jaccard"][key] = round(j, 4)
            rep["intersection"][key] = sorted(inter)
            rep["only_in"][f"{m1}_not_{m2}"] = sorted(only1)
            rep["only_in"][f"{m2}_not_{m1}"] = sorted(only2)
    return rep


# ---------------------------------------------------------------------------
# Main audit driver
# ---------------------------------------------------------------------------

def audit_symbol(
    symbol: str,
    out_dir: Path,
    baseline_dir: str = None,
    parquet_dir: str = "data_cache",
    model_dir: str = "regime_models",
) -> Dict:
    print(f"\n{'='*70}")
    print(f"AUDIT {symbol}")
    print(f"{'='*70}")
    result = {"symbol": symbol, "modes": {}}

    # Mode A — extract from existing CSV
    print(f"  Mode A (CURRENT, ~5000 bars hardcoded)...")
    try:
        sig_a = extract_mode_a_signatures(symbol, baseline_dir=baseline_dir)
        result["modes"]["A_current_5000"] = {
            "signatures_global": sorted(sig_a),
            "n_signatures": len(sig_a),
            "source": "existing presets CSV",
        }
        print(f"    → {len(sig_a)} unique signatures")
    except FileNotFoundError as e:
        print(f"    SKIP: {e}")
        result["modes"]["A_current_5000"] = {"error": str(e)}
        return result

    # Mode B1 — full-history regime-agnostic
    print(f"  Mode B1 (FULL-HISTORY agnostic, USE_CLUSTERING=False)...")
    try:
        b1 = run_simulation_full_history(
            symbol, use_clustering=False,
            parquet_dir=parquet_dir, model_dir=model_dir,
        )
        result["modes"]["B1_full_agnostic"] = {
            "signatures_global": sorted(b1["signatures_global"]),
            "n_signatures": len(b1["signatures_global"]),
            "n_bars_total": b1["n_bars_total"],
            "time_range": b1["time_range"],
            "elapsed_s": round(b1["elapsed_s"], 2),
        }
        print(f"    → {len(b1['signatures_global'])} signatures over {b1['n_bars_total']} bars in {b1['elapsed_s']:.1f}s")
    except Exception as e:
        print(f"    ERROR: {e}")
        result["modes"]["B1_full_agnostic"] = {"error": str(e)}
        b1 = None

    # Mode B2 — full-history per-cluster
    print(f"  Mode B2 (FULL-HISTORY per-cluster, USE_CLUSTERING=True)...")
    try:
        b2 = run_simulation_full_history(
            symbol, use_clustering=True,
            parquet_dir=parquet_dir, model_dir=model_dir,
        )
        per_cluster_serializable = {
            str(k): sorted(v) for k, v in b2["signatures_per_cluster"].items()
        }
        result["modes"]["B2_full_per_cluster"] = {
            "signatures_global": sorted(b2["signatures_global"]),
            "signatures_per_cluster": per_cluster_serializable,
            "signatures_union": sorted(b2["signatures_union"]),
            "n_signatures_union": len(b2["signatures_union"]),
            "n_bars_total": b2["n_bars_total"],
            "n_clusters": b2["n_clusters"],
            "time_range": b2["time_range"],
            "elapsed_s": round(b2["elapsed_s"], 2),
        }
        print(f"    → union {len(b2['signatures_union'])} signatures over {b2['n_bars_total']} bars in {b2['elapsed_s']:.1f}s")
        for k, sigs in b2["signatures_per_cluster"].items():
            print(f"      cluster {k}: {len(sigs)} sigs")
    except Exception as e:
        print(f"    ERROR: {e}")
        result["modes"]["B2_full_per_cluster"] = {"error": str(e)}
        b2 = None

    # Overlap report
    pools = {"A": sig_a}
    if b1:
        pools["B1"] = b1["signatures_global"]
    if b2:
        pools["B2_union"] = b2["signatures_union"]
        pools["B2_global"] = b2["signatures_global"]
    result["overlap"] = overlap_report(pools)
    print("\n  Overlap (Jaccard):")
    for k, v in result["overlap"]["jaccard"].items():
        print(f"    {k}: {v}")

    # Persist per-symbol JSON
    out_path = out_dir / f"audit_{symbol.replace('/', '_').replace('USDT','')}.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print(f"  → {out_path}")
    return result


def write_csvs_for_symbol(symbol: str, out_dir: Path,
                            parquet_dir: str = "data_cache",
                            model_dir: str = "regime_models") -> Dict[str, Path]:
    """Generate B1 (agnostic) and B2 (per-cluster) presets CSVs for symbol.

    Writes:
        out_dir/B1/presets_<SYM>USDT.csv
        out_dir/B2/presets_<SYM>USDT.csv

    Returns dict {'B1': path, 'B2': path}.
    """
    sym_clean = symbol.replace("/", "").replace("USDT", "")
    paths = {}

    print(f"  generating B1 CSV ({symbol})...")
    b1 = run_simulation_full_history(
        symbol, use_clustering=False,
        parquet_dir=parquet_dir, model_dir=model_dir,
        return_full_results=True,
    )
    p_b1 = out_dir / "B1" / f"presets_{sym_clean}USDT.csv"
    write_presets_csv(p_b1, b1["global_results"], cluster_results=None)
    print(f"    → {p_b1} ({len(b1['global_results'])} rows, {b1['elapsed_s']:.1f}s)")
    paths["B1"] = p_b1

    print(f"  generating B2 CSV ({symbol})...")
    b2 = run_simulation_full_history(
        symbol, use_clustering=True,
        parquet_dir=parquet_dir, model_dir=model_dir,
        return_full_results=True,
    )
    p_b2 = out_dir / "B2" / f"presets_{sym_clean}USDT.csv"
    n_cluster_rows = sum(len(v) for v in b2["cluster_results"].values())
    write_presets_csv(p_b2, b2["global_results"], cluster_results=b2["cluster_results"])
    print(f"    → {p_b2} ({len(b2['global_results'])} global + {n_cluster_rows} cluster rows, {b2['elapsed_s']:.1f}s)")
    paths["B2"] = p_b2
    return paths


def main():
    p = argparse.ArgumentParser(description="Audit lab_lite TOTAL_CANDLES window scope")
    p.add_argument("--symbols", nargs="+",
                    default=["BTC/USDT", "ONDO/USDT", "SOL/USDT"],
                    help="symbols to audit (default: BTC + ONDO + SOL)")
    p.add_argument("--baseline-dir", default=None,
                    help="dir with backed-up presets CSV (defaults to output/production)")
    p.add_argument("--parquet-dir", default="data_cache",
                    help="dir with full-history parquet files")
    p.add_argument("--model-dir", default="regime_models",
                    help="dir with GMM regime models")
    p.add_argument("--out", default=None,
                    help="output dir (default: audit_lab_lite_results_<TS>)")
    p.add_argument("--write-csvs", action="store_true",
                    help="Write B1/B2 presets CSV in productive format (consumable by "
                          "regime_walk_forward.py --presets-dir <out>/B1|B2)")
    args = p.parse_args()

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out_dir = Path(args.out or f"audit_lab_lite_results_{ts}")
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"OUTPUT DIR: {out_dir}")

    summary = {"ts": ts, "symbols": [], "per_symbol": {}}

    if args.write_csvs:
        print(f"\n[mode] write_csvs → emitting B1/B2 productive CSVs for {args.symbols}")
        for sym in args.symbols:
            paths = write_csvs_for_symbol(
                sym, out_dir,
                parquet_dir=args.parquet_dir,
                model_dir=args.model_dir,
            )
            summary["per_symbol"][sym] = {"csv_paths": {k: str(v) for k, v in paths.items()}}
            summary["symbols"].append(sym)
        with open(out_dir / "summary_csvs.json", "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2, default=str)
        print(f"\n✓ CSV generation complete — {out_dir}/")
        return 0

    for sym in args.symbols:
        r = audit_symbol(
            sym, out_dir,
            baseline_dir=args.baseline_dir,
            parquet_dir=args.parquet_dir,
            model_dir=args.model_dir,
        )
        summary["symbols"].append(sym)
        summary["per_symbol"][sym] = r

    # Aggregate summary table
    print(f"\n{'='*70}")
    print("SUMMARY TABLE — Jaccard overlap CURRENT(A) vs B1 vs B2")
    print(f"{'='*70}")
    print(f"{'SYMBOL':<12} | {'|A|':>4} | {'|B1|':>4} | {'|B2u|':>5} | {'A∩B1':>6} | {'A∩B2u':>6} | {'B1∩B2u':>7}")
    print("-" * 70)
    for sym, r in summary["per_symbol"].items():
        ov = r.get("overlap", {}).get("jaccard", {})
        sizes = r.get("overlap", {}).get("sizes", {})
        a = sizes.get("A", 0)
        b1n = sizes.get("B1", 0)
        b2u = sizes.get("B2_union", 0)
        ab1 = ov.get("A_vs_B1", "-")
        ab2 = ov.get("A_vs_B2_union", "-")
        b1b2 = ov.get("B1_vs_B2_union", "-")
        print(f"{sym:<12} | {a:>4} | {b1n:>4} | {b2u:>5} | {ab1:>6} | {ab2:>6} | {b1b2:>7}")

    with open(out_dir / "summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, default=str)

    print(f"\n✓ Audit complete — {out_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
