"""Contamination per-trade decomposition (PARTE B Ricardo cardinal 2026-05-26).

Decomposes pf_fwd of top-1 specialists into INSIDE/OUTSIDE the lab_lite 5K
window, using the SAME productive kernel chain (lab.precalculate_all_data +
lab.run_on_slice + build_regime_labels) — NO divergent reimplementation.

Gate of fidelity:
  G.3 — sanity reproduce aggregate pf_fwd of top-1 specialist == JSON (diff ~0).
        If FAILS for any cell, halt Tier 3 (tool diverges from productive kernel).

Per (sym, mode, cluster):
  1. Parse preset from JSON preset_label
  2. Decode config_id top-1
  3. precalculate_all_data(df, preset, hyst_mult, symbol)
  4. run_on_slice(..., return_per_trade=True) for SINGLE config
  5. Extract trades, filter to fwd_label of cluster k
  6. Partition by entry_bar in [n-5000, n)
  7. Compute pf_INSIDE / pf_OUTSIDE
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path
import numpy as np
import pandas as pd
import joblib

import lab_historico_numba_v8_3 as lab
import regime_walk_forward as rwf
import lab_lite_zonas_v5e as ll  # only for find_preset_in_csv lookup

# Caveat #22 §13.2 remediación 2026-05-30: forzar paridad CONFIG productiva
# (toxic_tail ya se pasa explícito vía PROD_* abajo; esto fuerza TRAIN_RATIO/MIN_EPISODE_BARS).
from master import CONFIG as _PROD_CONFIG
rwf.TRAIN_RATIO = _PROD_CONFIG['train_ratio']
rwf.MIN_EPISODE_BARS = _PROD_CONFIG['min_episode_bars']


LL_WINDOW = 5000

# Productive toxic_tail dynamic params (verified primary source master.py CONFIG +
# regime_walk_forward.py:541-546 call site)
PROD_TOXIC_TAIL = 0          # 0 in dynamic mode (gmm_probs drives it)
PROD_CONFIRM_THRESHOLD = 0.75
PROD_MAX_TOXIC_TAIL = 100
PROD_MIN_TOXIC_TAIL = 5


def parse_preset_label(preset_label: str) -> tuple:
    """Parse 'VIDYA(16)/SMA(60)_H00' → (fast_type, fast_period, ..., hyst_mult).

    Trend is derived as slow×4 (same type), matching lab_lite v5e
    result_to_preset_tuple convention.

    Returns:
        (preset_tuple_12, hyst_mult)
        preset_tuple_12: (fast_type_str, fast_p, fast_p1, fast_p2,
                           slow_type_str, slow_p, slow_p1, slow_p2,
                           trend_type_str, trend_p, trend_p1, trend_p2)
        hyst_mult: float (0.0 or 0.5)
    """
    # Pattern: TYPE(period)/TYPE(period)_HXX
    m = re.match(r"([A-Za-z0-9]+)\((\d+)\)/([A-Za-z0-9]+)\((\d+)\)_H(\d{2})", preset_label)
    if not m:
        raise ValueError(f"Cannot parse preset_label: {preset_label}")
    fast_type, fast_p, slow_type, slow_p, hyst_code = m.groups()
    fast_p = int(fast_p)
    slow_p = int(slow_p)
    hyst_mult = float(hyst_code) / 10.0  # H00 → 0.0, H05 → 0.5
    # Trend = slow×4 same type, matches result_to_preset_tuple
    trend_type = slow_type
    trend_p = slow_p * 4
    # ALMA/T3/JMA need p1/p2 — but preset_label drops them. For productive,
    # lab_lite generates preset CSV with explicit p1/p2. For audit re-sim from
    # JSON we have to look up in original presets CSV. Defer this.
    preset_tuple = (fast_type, fast_p, 0.0, 0.0,
                     slow_type, slow_p, 0.0, 0.0,
                     trend_type, trend_p, 0.0, 0.0)
    return preset_tuple, hyst_mult


def lookup_preset_from_csv(config_id: int, preset_csv_path: Path) -> tuple:
    """Look up full preset tuple (with p1/p2) + hyst from CSV by config_id.

    Productive lab_lite presets CSV has explicit fast_p1, fast_p2, slow_p1, slow_p2,
    trend_type, trend_period, trend_p1, trend_p2 — required for ALMA/T3/JMA.

    The CSV doesn't index by config_id (config_id is generated by WF), but
    preset_label has the type+period+hyst info. Use preset_label match to find
    p1/p2 for ALMA/T3/JMA.

    For now, simpler: walk the CSV and find the row whose (fast_type, fast_p,
    slow_type, slow_p) matches our preset_label. Use first match's p1/p2.
    """
    df = pd.read_csv(preset_csv_path)
    return df


def build_preset_from_csv_row(row: pd.Series) -> tuple:
    """Build 12-tuple preset from presets CSV row."""
    return (
        str(row['fast_type']), int(row['fast_period']),
        float(row['fast_p1']), float(row['fast_p2']),
        str(row['slow_type']), int(row['slow_period']),
        float(row['slow_p1']), float(row['slow_p2']),
        str(row['trend_type']), int(row['trend_period']),
        float(row['trend_p1']), float(row['trend_p2']),
    )


def find_preset_in_csv(csv_path: Path, preset_label: str) -> tuple:
    """Match preset_label (e.g. 'VIDYA(16)/SMA(60)_H00') to row in productive
    presets CSV, return full 12-tuple preset + hyst_mult.

    preset_label encodes fast_type/fast_period/slow_type/slow_period/hyst — but
    NOT p1/p2. The CSV may have multiple rows matching same (fast,slow) tuple
    with different p1/p2 (e.g. ALMA variants). Pick first match — this is good
    for non-parameterized MAs (SMA/EMA/VIDYA etc), and for ALMA/T3/JMA the JSON
    config_id encodes the variant uniquely.

    For audit purposes, exact p1/p2 are reproducible from preset_label IF the MA
    type has fixed params. For ALMA/T3/JMA we'll use the first matching row.
    """
    m = re.match(r"([A-Za-z0-9]+)\((\d+)\)/([A-Za-z0-9]+)\((\d+)\)_H(\d{2})", preset_label)
    if not m:
        raise ValueError(f"Cannot parse: {preset_label}")
    fast_type, fast_p, slow_type, slow_p, hyst_code = m.groups()
    fast_p, slow_p = int(fast_p), int(slow_p)
    hyst_mult = float(hyst_code) / 10.0

    df = pd.read_csv(csv_path)
    matches = df[
        (df['fast_type'] == fast_type) & (df['fast_period'] == fast_p) &
        (df['slow_type'] == slow_type) & (df['slow_period'] == slow_p)
    ]
    if len(matches) == 0:
        raise ValueError(f"No CSV match for {preset_label} in {csv_path}")
    row = matches.iloc[0]
    return build_preset_from_csv_row(row), hyst_mult


def load_full_parquet(symbol: str, parquet_dir: str = "data_cache") -> pd.DataFrame:
    sym_clean = symbol.replace("/", "").replace("USDT", "")
    p = Path(parquet_dir) / f"{sym_clean}USDT_1h.parquet"
    df = pd.read_parquet(p)
    if "timestamp" not in df.columns and "timestamp_ms" in df.columns:
        df = df.rename(columns={"timestamp_ms": "timestamp"})
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
    cols = ["timestamp", "open", "high", "low", "close", "volume"]
    return df[cols].reset_index(drop=True)


def decompose_specialist(symbol: str, mode: str, cluster_k: int,
                          spec_json_path: Path, preset_csv_path: Path,
                          df: pd.DataFrame, regime_labels: np.ndarray,
                          cluster_labels_base: np.ndarray, n_clusters: int,
                          n_doubled: int, ll_start: int) -> dict:
    """Decompose top-1 of (sym, mode, cluster_k) into INSIDE/OUTSIDE pf_fwd."""
    with open(spec_json_path) as f:
        d = json.load(f)
    cl = d["clusters"].get(str(cluster_k))
    if not cl or not cl.get("top_configs"):
        return {"error": "no top_config", "sym": symbol, "mode": mode, "k": cluster_k}
    top1 = cl["top_configs"][0]
    config_id = int(top1["config_id"])
    preset_label = top1["preset"]
    expected_pf_fwd = float(top1.get("pf_fwd", 0))
    expected_trades_fwd = int(top1.get("trades_fwd", 0))
    expected_pnl_fwd = float(top1.get("pnl_fwd", 0))

    # Find preset in CSV (with full p1/p2 for ALMA/T3/JMA)
    try:
        preset_tuple, hyst_mult = find_preset_in_csv(preset_csv_path, preset_label)
    except Exception as e:
        return {"error": f"preset_lookup_fail: {e}", "sym": symbol, "mode": mode, "k": cluster_k}

    # Precalculate (same as productive)
    data = lab.precalculate_all_data(df, preset=preset_tuple, hyst_mult=hyst_mult, symbol=symbol)

    # Single config
    configs = np.array([config_id], dtype=np.uint32)

    # Run simulation (same as productive — return per-trade)
    aggregates, per_trade = lab.run_on_slice(
        configs, data, 0, len(data['close']),
        lab.SL_PERCENT, lab.SL_EMERGENCY_PERCENT, lab.TS_PERCENT,
        lab.COOLDOWN_BARS, lab.COMMISSION_ROUND_TRIP,
        cluster_labels=regime_labels, n_clusters=n_doubled,
        return_per_trade=True,
    )
    results, cl_pnl, cl_trades, cl_wins, cl_maxdd, cl_gp, cl_gl = aggregates

    # Compute aggregate pf_fwd to confirm reproduces JSON (G.3 sanity)
    k_fwd_label = cluster_k + n_clusters
    repro_pnl_fwd = float(cl_pnl[0, k_fwd_label])
    repro_trades_fwd = int(cl_trades[0, k_fwd_label])
    repro_gp = float(cl_gp[0, k_fwd_label])
    repro_gl = float(cl_gl[0, k_fwd_label])
    repro_pf = (repro_gp / repro_gl) if repro_gl > 0 else (5.0 if repro_gp > 0 else 0.0)

    # Per-trade arrays
    n_trades_total = int(per_trade["count"][0])
    entries = per_trade["entry_bar"][0, :n_trades_total].astype(int)
    pnls = per_trade["pnl"][0, :n_trades_total]
    trade_clusters = per_trade["cluster"][0, :n_trades_total].astype(int)

    # Filter to fwd label of cluster k (trades that opened in fwd episodes of cluster k)
    fwd_mask = (trade_clusters == k_fwd_label)
    fwd_entries = entries[fwd_mask]
    fwd_pnls = pnls[fwd_mask]

    # Partition by entry_bar inside [ll_start, n) vs outside
    inside_mask = fwd_entries >= ll_start
    outside_mask = ~inside_mask
    n_inside = int(inside_mask.sum())
    n_outside = int(outside_mask.sum())
    pnls_inside = fwd_pnls[inside_mask]
    pnls_outside = fwd_pnls[outside_mask]

    def pf_from_pnls(pnls_arr):
        if len(pnls_arr) == 0:
            return None, 0, 0, 0
        gp = float(pnls_arr[pnls_arr > 0].sum())
        gl = float(-pnls_arr[pnls_arr < 0].sum())
        wins = int((pnls_arr > 0).sum())
        if gl > 0:
            return gp / gl, gp, gl, wins
        elif gp > 0:
            return float("inf"), gp, gl, wins
        return 0.0, gp, gl, wins

    pf_in, gp_in, gl_in, wins_in = pf_from_pnls(pnls_inside)
    pf_out, gp_out, gl_out, wins_out = pf_from_pnls(pnls_outside)
    pf_all, _, _, _ = pf_from_pnls(fwd_pnls)

    result = {
        "sym": symbol, "mode": mode, "k": cluster_k,
        "config_id": config_id, "preset_label": preset_label,
        "expected_pf_fwd": expected_pf_fwd,
        "expected_trades_fwd": expected_trades_fwd,
        "expected_pnl_fwd": expected_pnl_fwd,
        "repro_pf_fwd": repro_pf,
        "repro_trades_fwd": repro_trades_fwd,
        "repro_pnl_fwd": repro_pnl_fwd,
        "repro_diff_pf_pct": abs(repro_pf - expected_pf_fwd) / max(0.001, expected_pf_fwd) * 100,
        "n_trades_total": n_trades_total,
        "n_trades_fwd_extracted": int(fwd_mask.sum()),
        "n_inside": n_inside, "n_outside": n_outside,
        "pf_inside": pf_in, "gp_inside": gp_in, "gl_inside": gl_in,
        "wins_inside": wins_in,
        "pf_outside": pf_out, "gp_outside": gp_out, "gl_outside": gl_out,
        "wins_outside": wins_out,
        "pf_all_extracted": pf_all,
    }
    return result


def main():
    audit_dir = Path("audit_etapa2_20260522_213747")
    out_path = audit_dir / "contamination_part_b.json"

    syms = ["BTC/USDT", "ETH/USDT", "BNB/USDT", "SEI/USDT", "POL/USDT", "ONDO/USDT"]
    modes = ["A", "B2"]

    all_results = []
    print(f"\n{'='*120}")
    print("PER-TRADE CONTAMINATION DECOMPOSITION — same productive kernel chain")
    print(f"{'='*120}\n")

    for sym in syms:
        sym_clean = sym.replace("/", "").replace("USDT", "")
        print(f"\n--- {sym} ---")
        df = load_full_parquet(sym)
        n_bars = len(df)
        ll_start = max(0, n_bars - LL_WINDOW)

        # Productive cluster labels + GMM probs (regime_walk_forward path)
        sym_key = sym.replace("/USDT", "").replace("/", "")
        model_path = Path("regime_models") / f"{sym_key}_regime.joblib"
        model_data = joblib.load(model_path)
        cluster_labels_base, n_clusters = rwf.compute_cluster_labels(df, model_data)
        gmm_probs = rwf.compute_gmm_probs(df, model_data)

        # Build doubled labels with PRODUCTIVE dynamic toxic_tail config
        episodes = rwf.identify_episodes(cluster_labels_base, n_clusters,
                                          min_bars=rwf.MIN_EPISODE_BARS)
        regime_labels, n_doubled, split_info = rwf.build_regime_labels(
            cluster_labels_base, episodes, n_clusters,
            train_ratio=rwf.TRAIN_RATIO,
            toxic_tail=PROD_TOXIC_TAIL,
            gmm_probs=gmm_probs,
            confirm_threshold=PROD_CONFIRM_THRESHOLD,
            max_toxic_tail=PROD_MAX_TOXIC_TAIL,
            min_toxic_tail=PROD_MIN_TOXIC_TAIL,
        )
        # Diagnostic: toxic_tail stats per cluster
        for k in range(n_clusters):
            si = split_info.get(k, {})
            if si.get("valid"):
                tt_mean = si.get("toxic_tail_mean", 0)
                print(f"  C{k}: train={si['train_episodes']} eps ({si['train_bars']} bars) "
                      f"| fwd={si['fwd_episodes']} eps ({si['fwd_bars']} bars) "
                      f"| toxic mean={tt_mean:.0f}")

        for mode in modes:
            if mode == "A":
                spec_path = audit_dir / "baseline_A_deployed" / f"{sym_clean}USDT_specialist_configs.json"
                csv_path = audit_dir / "baseline_A_deployed" / f"presets_{sym_clean}USDT.csv"
            else:
                # P4 dynamic toxic_tail B2 specialists (apples-to-apples vs A)
                spec_path = audit_dir / f"wf_B2_dyn_{sym_clean}" / f"{sym_clean}USDT_specialist_configs.json"
                csv_path = audit_dir / "B2" / f"presets_{sym_clean}USDT.csv"
            if not spec_path.exists() or not csv_path.exists():
                print(f"  {sym} {mode}: skip (missing files)")
                continue
            for k in range(n_clusters):
                try:
                    r = decompose_specialist(
                        sym, mode, k, spec_path, csv_path, df,
                        regime_labels, cluster_labels_base, n_clusters,
                        n_doubled, ll_start,
                    )
                except Exception as e:
                    print(f"  {sym} {mode} C{k}: ERROR {e}")
                    continue
                all_results.append(r)
                if "error" in r:
                    print(f"  {sym} {mode} C{k}: {r['error']}")
                else:
                    print(f"  {sym} {mode} C{k}: cfg={r['config_id']} fwd_trades={r['n_trades_fwd_extracted']} "
                          f"(in={r['n_inside']}, out={r['n_outside']}) "
                          f"PF_in={r['pf_inside']} PF_out={r['pf_outside']} "
                          f"(JSON pf_fwd={r['expected_pf_fwd']:.3f}, repro={r['repro_pf_fwd']:.3f}, "
                          f"diff={r['repro_diff_pf_pct']:.1f}%)")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2, default=str)
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
